--- #YAML:1.0
name:               threads
version:            1.79
abstract:           Perl interpreter-based threads
author:
    - Artur Bergman, Jerry D. Hedden <jdhedden AT cpan DOT org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:               0
    Config:             0
    ExtUtils::testlib:  0
    Hash::Util:         0
    IO::File:           0
    overload:           0
    strict:             0
    Test::More:         0
    warnings:           0
    XSLoader:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.5601
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
