# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         threads
version:      1.37
version_from: threads.pm
installdirs:  perl
requires:
    XSLoader:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
