---
abstract: 'Perl interpreter-based threads'
author:
  - 'Artur Bergman, Jerry D. Hedden <jdhedden AT cpan DOT org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: threads
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Config: 0
  ExtUtils::testlib: 0
  Hash::Util: 0
  IO::File: 0
  Test::More: 0
  XSLoader: 0
  overload: 0
  strict: 0
  warnings: 0
version: 1.86
