--- #YAML:1.0
name:                threads
version:             1.17
abstract:            Perl interpreter-based threads
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Artur Bergman <sky AT crucially DOT net>
distribution_type:   module
requires:     
    threads::shared:               0
    XSLoader:                      0
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
