--- #YAML:1.0
name:                threads
version:             1.43
abstract:            Perl interpreter-based threads
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.30_04
author:              Artur Bergman, Jerry D. Hedden <jdhedden AT cpan DOT org>
distribution_type:   module
requires:     
    Carp:                          0
    Config:                        0
    ExtUtils::testlib:             0
    Hash::Util:                    0
    IO::File:                      0
    overload:                      0
    strict:                        0
    warnings:                      0
    XSLoader:                      0
meta-spec:
    url: http://module-build.sourceforge.net/META-spec-new.html
    version: 1.1
